//
//  PBXCompilerSpecificationGccLogging.h
//  XCodeHaskellSupport
//
//  Created by André Pang on Fri May 21 2004.
//  Copyright (c) 2004 __MyCompanyName__. All rights reserved.
//

#import <Foundation/Foundation.h>

#import "PBXCompilerSpecification.h"
#import "PBXCompilerSpecificationYacc.h"

static Class shadowed_PBXCompilerSpecificationYacc;

static IMP shadowed_initWithPropertyListDictionary_;
static IMP shadowed_acceptsInputFileType_;
static IMP shadowed_effectiveCompilerSpecificationForFileNamed_inTargetBuildContext_;
static IMP shadowed_computeDependenciesForFilePaths_outputDirectory_inTargetBuildContext_;
static IMP shadowed_uniqueOutputBaseNameForInputFilePath_inTargetBuildContext_;
static IMP shadowed_outputFilesForInputFilePath_inTargetBuildContext_;
static IMP shadowed_effectiveCompilerSpecificationForFileNamed_ofType_inTargetBuildContext_;
static IMP shadowed_computeDependenciesForInputFile_ofType_variant_architecture_outputDirectory_inTargetBuildContext_;
static IMP shadowed_computeDependenciesForFilePath_ofType_outputDirectory_inTargetBuildContext_;
static IMP shadowed_executablePathInTargetBuildContext_;
static IMP shadowed_effectiveCompilerSpecificationForFileNamed_ofType_inTargetBuildContext_;
static IMP shadowed_precompileHeaderFileAtPath_forSourceFileOfType_withExtraFlags_toPrecompPath_inTargetBuildContext_;
static IMP shadowed_compileSourceCodeFileAtPath_ofType_toOutputDirectory_inTargetBuildContext_;
static IMP shadowed_fileTypeForGccLanguageDialect_;
static IMP shadowed_computeDependenciesForInputFile_ofType_variant_architecture_outputDirectory_inTargetBuildContext_;
static IMP shadowed_computeDependenciesForFilePath_ofType_outputDirectory_inTargetBuildContext_;
static IMP shadowed_perSpecificationFlagsInTargetBuildContext_;
static IMP shadowed_optionalFrameworkSearchPathsInBuildContext_;
static IMP shadowed_optionalHeaderSearchPathsInBuildContext_;
static IMP shadowed_messageLengthFlagInTargetBuildContext_;
static IMP shadowed_zeroLinkFlagInTargetBuildContext_;
static IMP shadowed_fixAndContinueFlagInTargetBuildContext_;
static IMP shadowed_dynamicNoPicFlagInTargetBuildContext_;
static IMP shadowed_distributedBuildFlagsInTargetBuildContext_;
static IMP shadowed_perCompilerStandardBuildFlagsInTargetBuildContext_;
static IMP shadowed_additionalEnvironmentEntriesInTargetBuildContext_;
static IMP shadowed_standardFlagsInTargetBuildContext_;
static IMP shadowed_otherFlagsInTargetBuildContext_;
static IMP shadowed_precompFileNameForHeaderPath_inTargetBuildContext_;
static IMP shadowed_flagsForIncludingPrecompiledPrefixHeaderAtPath_inTargetBuildContext_;
static IMP shadowed_symrepFileNameForHeaderPath_inTargetBuildContext_;
static IMP shadowed_subprocessCommandLineForPreprocessingBehaviorWithNode_commandLine_;
static IMP shadowed_precompileHeaderFileAtPath_forSourceFileOfType_withExtraFlags_toPrecompPath_inTargetBuildContext_;
static IMP shadowed_symbolizeHeaderFileAtPath_forSourceFileOfType_withExtraFlags_toSymbolSeparationRepositoryPath_inTargetBuildContext_;
static IMP shadowed_compileSourceCodeFileAtPath_ofType_toOutputDirectory_inTargetBuildContext_;
