=head1 Accessing Other Frameworks from Haskell

This section is not written yet: please write to the I<hoc-users>
mailing list (see L<http://hoc.sourceforge.net/support.html>) for
assistance or, have a look at the HOC source code yourself.

=begin comment

TODO :)

=for comment =head2 Using F<ifgen>

=for comment =head3 Binding Scripts

=end comment

