TITLE = HOC: a Haskell to Objective-C bridge

HOC.html: Creating\ an\ Objective-C\ Class\ in\ Haskell.pod
	pod2html \
	  --netscape \
	  --index \
	  --title="${TITLE}" \
	  --outfile "$@" \
	  "$<"

clean:
	-rm HOC.html pod2htm*

