=head1 Tools

=head2 F<hoc-wrap>

The F<hoc-wrap> tool takes an executable and "wraps" it in a Mac OS
X F<.app> application bundle. It expects to find a F<Contents/> folder
that already contains all the necessary ingredients for the bundle,
except for the executable itself, in the current directory.

See C<hoc-wrap --help> for the definitive reference on F<hocwrap>.

=for comment Modeline for vi(m)
vi:sw=2 tw=65

